export { HeaderNav } from "./HeaderNav";
export { HeroSection } from "./HeroSection";
export { StatsSection } from "./StatsSection";
export { FeaturesSection } from "./FeaturesSection";
export { PlatformSection } from "./PlatformSection";
export { PricingSection } from "./PricingSection";
export { TestimonialsSection } from "./TestimonialsSection";
export { CTASection } from "./CTASection";
export { FooterSection } from "./FooterSection";
